delete from AlertDefinitions
delete from AlertDetails
delete from AlertDeviceTypes
delete from AlertEvents
delete from AlertLocations
delete from AlertNames
delete from AlertServers
delete from BlackBerry
delete from Company
delete from DominoCluster
delete from DominoDiskSettings
delete from DominoServers
delete from Locations
delete from LogFile
delete from Logos
delete from MailServices
delete from Maintenance
delete from MaintenanceSettings
delete from MaintenanceWindows
delete from Network Devices
delete from NotesDatabases
delete from NotesMailProbe
delete from SametimeServers
delete from SametimeUsers
delete from ScheduledCommands
delete from ScheduledReports
delete from ServerMaintenance
delete from Servers
delete from ServerTaskSettings
delete from URLs
delete from UserCustomPages
delete from UserLocationRestrictions
delete from UserMenuRestrictions
delete from UserReportFavorites
delete from Users
delete from UserServerRestrictions
delete from UserServerTypeRestrictions
delete from AlertHistory
delete from AlertSentDetails
delete from BBHistory
delete from BlackBerry Users
delete from BlackBerryServers
delete from DiskSpace
delete from DNS_Servers
delete from DominoClusterHealth
delete from DominoConsoleCommands
delete from DominoDiskSpace
delete from DominoServerTaskStatus
delete from MailHealth
delete from NotesMailProbeHistory
delete from Status
delete from Traveler_Devices
delete from Traveler_Status
